#!/usr/bin/env python3
"""Generate hist.js: ~6 years of split/dividend-adjusted daily closes plus
real past earnings-report dates for the Time-machine tab.

Needs yfinance (unlike refresh_data.py, this is a run-once/rarely script —
historical data doesn't go stale the way option chains do; rerun it when you
want to extend the window).

Usage:  python3 build_history.py
"""
import datetime as dt
import json
import os

import yfinance as yf

TICKERS = ["NVDA", "TSLA", "AAPL", "MSFT", "AMD", "SPY"]
PERIOD = "6y"
HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    frames, earnings = {}, {}
    for tk in TICKERS:
        t = yf.Ticker(tk)
        h = t.history(period=PERIOD, auto_adjust=True)["Close"].dropna()
        h.index = [d.date() for d in h.index]
        frames[tk] = h
        try:
            ed = t.get_earnings_dates(limit=40)
            past = sorted({d.date().isoformat() for d in ed.index
                           if d.date() < dt.date.today()}) if ed is not None else []
        except Exception:
            past = []
        earnings[tk] = past
        print(f"{tk}: {len(h)} closes {h.index[0]} → {h.index[-1]}, {len(past)} earnings dates")

    # one shared NYSE trading calendar: dates present in every series
    dates = sorted(set.intersection(*[set(f.index) for f in frames.values()]))
    assert len(dates) > 1000, f"only {len(dates)} common trading days"
    data = {
        "asof": dt.date.today().isoformat(),
        "dates": [d.isoformat() for d in dates],
        "tickers": {},
    }
    for tk in TICKERS:
        closes = [round(float(frames[tk][d]), 3) for d in dates]
        assert all(c > 0 for c in closes), f"{tk}: bad close"
        # keep only earnings dates that fall inside the price window
        lo, hi = dates[0].isoformat(), dates[-1].isoformat()
        data["tickers"][tk] = {
            "closes": closes,
            "earnings": [e for e in earnings[tk] if lo <= e <= hi],
        }

    js = ("/* Historical daily closes (split/dividend-adjusted) + real past\n"
          "   earnings dates for the Time-machine tab. Regenerated by\n"
          "   build_history.py — do not edit by hand. */\n"
          "/*==DATA-START==*/\n"
          f"const HIST_DATA = {json.dumps(data, separators=(',', ':'))};\n"
          "/*==DATA-END==*/\n")
    path = os.path.join(HERE, "hist.js")
    with open(path, "w") as f:
        f.write(js)
    print(f"wrote {path} ({len(js)/1024:.0f} KB, {len(dates)} shared trading days)")


if __name__ == "__main__":
    main()
