#!/usr/bin/env python3
"""Regenerate data.js with real (delayed) option-chain snapshots from Cboe.

Zero third-party dependencies (stdlib urllib only). For each ticker in
TICKERS it downloads the full delayed chain from
https://cdn.cboe.com/api/global/delayed_quotes/options/<TICKER>.json,
keeps the expiries nearest to DTE_TARGETS and strikes within
STRIKE_BAND of spot, and writes the compact result into data.js.
Each option row is [strike, mid, iv, delta, bid, ask, open_interest]
(consumers may index only the first four — extra fields are additive).
(a `const CHAIN_DATA = {...}` between the ==DATA-START/END== markers,
loaded via <script src> so the page still works over file://).

Any failed sanity check aborts with a nonzero exit so the CI refresh
never commits a broken snapshot.

Usage:  python3 refresh_data.py
"""
import datetime as dt
import json
import os
import re
import sys
import urllib.request

TICKERS = ["NVDA", "TSLA", "AAPL", "MSFT", "AMD", "SPY"]
DTE_TARGETS = [7, 30, 60, 120, 240]   # pick the expiry nearest each target
STRIKE_BAND = 0.30                    # keep strikes within ±30% of spot
MIN_STRIKES = 10                      # per side per expiry, else drop the expiry
MIN_EXPIRIES = 3                      # per ticker, else abort

OSYM = re.compile(r"^[A-Z.]+(\d{6})([CP])(\d{8})$")
HERE = os.path.dirname(os.path.abspath(__file__))


def fetch(ticker):
    url = f"https://cdn.cboe.com/api/global/delayed_quotes/options/{ticker}.json"
    req = urllib.request.Request(url, headers={"User-Agent": "options-gex-101-refresh"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def build(ticker, today):
    raw = fetch(ticker)["data"]
    spot = raw.get("current_price") or raw.get("close")
    assert spot and spot > 0, f"{ticker}: no spot price"
    chains = {}
    for o in raw["options"]:
        m = OSYM.match(o["option"])
        if not m:
            continue
        exp = dt.datetime.strptime(m.group(1), "%y%m%d").date()
        if exp <= today:
            continue
        strike = int(m.group(3)) / 1000
        if abs(strike - spot) / spot > STRIKE_BAND:
            continue
        bid, ask, iv = o.get("bid") or 0, o.get("ask") or 0, o.get("iv") or 0
        if ask <= 0 or iv <= 0.01:      # no market / broken IV → useless for pricing
            continue
        mid = round((bid + ask) / 2, 3)
        if mid <= 0:
            continue
        chains.setdefault(exp, {"C": [], "P": []})[m.group(2)].append(
            [round(strike, 2), mid, round(iv, 4), round(o.get("delta") or 0, 4),
             round(bid, 3), round(ask, 3), int(o.get("open_interest") or 0)])

    assert chains, f"{ticker}: empty chain"
    exps = sorted(chains)
    picked = []
    for t in DTE_TARGETS:
        best = min(exps, key=lambda e: abs((e - today).days - t))
        if best not in picked:
            picked.append(best)

    out = {}
    for e in sorted(picked):
        c = chains[e]
        c["C"].sort()
        c["P"].sort()
        if len(c["C"]) >= MIN_STRIKES and len(c["P"]) >= MIN_STRIKES:
            out[e.isoformat()] = c
    assert len(out) >= MIN_EXPIRIES, f"{ticker}: only {len(out)} usable expiries"
    return {"spot": round(spot, 2), "expiries": out}


def main():
    today = dt.date.today()
    data = {
        "asof": today.isoformat(),
        "source": "Cboe delayed quotes (cdn.cboe.com)",
        "tickers": {},
    }
    for tk in TICKERS:
        data["tickers"][tk] = build(tk, today)
        n = sum(len(c[s]) for c in data["tickers"][tk]["expiries"].values() for s in ("C", "P"))
        print(f"{tk}: spot {data['tickers'][tk]['spot']}, "
              f"{len(data['tickers'][tk]['expiries'])} expiries, {n} options")

    js = ("/* Real (delayed) option-chain snapshots for the Playground tab.\n"
          "   Regenerated by refresh_data.py — do not edit by hand. */\n"
          "/*==DATA-START==*/\n"
          f"const CHAIN_DATA = {json.dumps(data, separators=(',', ':'))};\n"
          "/*==DATA-END==*/\n")
    path = os.path.join(HERE, "data.js")
    with open(path, "w") as f:
        f.write(js)
    print(f"wrote {path} ({len(js)/1024:.0f} KB)")


if __name__ == "__main__":
    sys.exit(main())
